# Generated by Django 3.2.9 on 2022-11-29 14:26

import applications.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', applications.account.models.UserManager()),
            ],
        ),
    ]
